name: Lint
on: [push]

jobs:
  lint_on_linux:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10
      - name: Install dependencies
        run: npm install
      - name: Install prettier
        run: npm i -g prettier
      - name: Lint
        run: prettier -c .
